### ISSUE TITLE
Blocked host on development environment 

### ISSUE THREAD

**Issue by Verlich** [zombocom/derailed_benchmarks#236] opened 2024-05-06 17:18 UTC
RAILS_ENV=development bundle exec derailed exec perf:mem_over_time
Booting: development

Couldn't call app. Bad request to /! Resulted in 403 status.

***RESPONSE BODY***
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Action Controller: Exception caught</title>
  ...
</head>
<body>

<header>
  <h1>Blocked host: example.org</h1>
</header>
<div id="container">
  <h2>To allow requests to example.org make sure it is a valid hostname (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:</h2>
  <pre>config.hosts &lt;&lt; "example.org"</pre>
</div>


</body>
</html>
```
Already added example.org, example, and localhost to development.yml and not working.

**Comment by s01ipsist** [comment] 2024-05-08 05:27
Easy workaround is to just comment out the config entirely
```
# config.hosts ...
```

**Comment by pcai** [comment] 2024-09-30 15:02
dupe of #203

**Closed by pcai** 2024-09-30 15:02 UTC
